name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "6.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Publish
        shell: pwsh
        run: |
          dotnet publish -p:PublishSingleFile=true -p:CommitHash=${{ github.sha }} -p:CommitRef=${{ github.ref_type }}/${{ github.ref_name }} -p:DiscordApplicationId="${{ secrets.DISCORD_APPLICATION_ID }}" -r win-x64 -c Release --self-contained false .\Bloxstrap\Bloxstrap.csproj
          Rename-Item ".\Bloxstrap\bin\Release\net6.0-windows\win-x64\publish\Zeyadstrap.exe" "Zeyadstrap.exe" -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: Zeyadstrap
          path: .\Bloxstrap\bin\Release\net6.0-windows\win-x64\publish\Zeyadstrap.exe
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: Zeyadstrap
          path: release

      - name: Rename release binary
        run: mv release/Zeyadstrap.exe Zeyadstrap-${{ github.ref_name }}.exe

      - name: Create draft release
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          generate_release_notes: true
          files: Zeyadstrap-${{ github.ref_name }}.exe